Feature/docs update
wms-proj/wms-proj pull request #20
Opened 2017-05-14 06:12 UTC by VladimirLogachev

1. **NPM scripts** described in Readme
2. **db name** changed to `wms`

2017-05-14 16:16 UTC, mkarabashev commented
Looks good. Can you use the environmental variables in mockgoose?

2017-05-14 16:21 UTC, mkarabashev requested changes
use the env variables or the server/config.js file in mockgoose (server/util/test-helpers.js)

2017-05-16 04:31 UTC, VladimirLogachev commented
Now the word `localhost` can only be found in `config.js` for cases when env variable `MONGO_URL` is not set.

2017-05-16 19:40 UTC, mkarabashev approved these changes

2017-05-16 19:40 UTC, merged